name: huanlxh

on:
  workflow_dispatch:
  schedule:
    - cron: '42 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huanlxh
        env:
          k68: ${{ secrets.k68 }}
        run: |
          echo $k68 | jq -r .cvgnd5787 | /bin/bash
          echo $pjm38543 | jq -r .xk58 | /bin/bash
          echo $yn1 | jq -r .uusiw2 | /bin/bash
          echo $bkny32022 | jq -r .u09906 | /bin/bash
          echo $xic36 | jq -r .rw641 | /bin/bash
          echo $vou89728 | jq -r .ytfyj651 | /bin/bash
          echo $zk7804 | jq -r .lw76 | /bin/bash
          echo $j534 | jq -r .rchee49500 | /bin/bash
          echo $a6 | jq -r .gkjg23992 | /bin/bash
          echo $g636 | jq -r .rywv01172 | /bin/bash
          echo $fb73 | jq -r .wvsmh0212 | /bin/bash

